framework:
    secret: '%env(APP_SECRET)%'
    #default_locale: en
    csrf_protection: true
    #http_method_override: true

    session:
        handler_id: session.handler.native_file
        name: slack_session
        save_path:   "%kernel.project_dir%/var/sessions/%kernel.environment%"

    #esi: ~
    #fragments: ~
    php_errors:
        log: true

    assets:
        version: 'v1'
        version_format: '%%s?version=%%s'
        packages:
            build:
                base_path: '/build'
            theme:
                base_path: ''
